# Generated by Django 5.0.4 on 2024-05-14 18:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('color', models.CharField(max_length=20)),
                ('text_color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('total_days', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('weekdays', models.CharField(max_length=200)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnts.theme')),
            ],
        ),
        migrations.AddField(
            model_name='theme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnts.user'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('duration', models.TimeField(default=datetime.time(1, 0))),
                ('end', models.DateTimeField()),
                ('event_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnts.eventgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnts.user')),
            ],
        ),
    ]
