# Generated by Django 5.0.4 on 2024-05-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnts', '0002_alter_eventgroup_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='weekdays',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
