# Generated by Django 5.0.4 on 2024-05-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnts', '0003_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.TimeField(),
        ),
    ]
