# Generated by Django 5.0.4 on 2024-05-06 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnts', '0004_alter_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
    ]
